export const ADD_REMINDER = "ADD_REMINDER";
export const TOGGLE_LIST_MODAL = "TOGGLE_LIST_MODAL";
export const TOGGLE_FORM_MODAL = "TOGGLE_FORM_MODAL";
export const UPDATE_CURRENT_FORM = "UPDATE_CURRENT_FORM";
export const UPDATE_REMINDER = "UPDATE_CURRENT_REMINDER";
